# Generated by Django 4.0 on 2022-03-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemanagement',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='就業時刻'),
        ),
        migrations.AlterField(
            model_name='timemanagement',
            name='rest_time',
            field=models.FloatField(blank=True, null=True, verbose_name='休憩時間'),
        ),
    ]
