# Generated by Django 4.0 on 2022-03-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_management_app', '0002_alter_timemanagement_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemanagement',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='始業時刻'),
        ),
    ]
