# Generated by Django 4.0 on 2022-03-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_management_app', '0004_alter_timemanagement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemanagement',
            name='date',
            field=models.DateField(verbose_name='日付'),
        ),
        migrations.AddConstraint(
            model_name='timemanagement',
            constraint=models.UniqueConstraint(fields=('date', 'created_by'), name='date_unique_by_user'),
        ),
    ]
