# Generated by Django 4.0 on 2022-03-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_management_app', '0005_alter_timemanagement_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timemanagement',
            name='travel_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='交通費'),
        ),
        migrations.AddField(
            model_name='timemanagement',
            name='travel_remarks',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='交通費_備考'),
        ),
    ]
