# Generated by Django 4.0 on 2022-03-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_management_app', '0006_timemanagement_travel_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('content', models.CharField(max_length=255, verbose_name='お知らせ内容')),
            ],
        ),
    ]
